# Generated by Django 2.1.1 on 2018-09-10 07:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100, verbose_name='标题')),
                ('image', models.ImageField(blank=True, upload_to='media/newspictures', verbose_name='图片')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='日期')),
                ('create_time', models.DateField(default=django.utils.timezone.now, verbose_name='创建日期')),
                ('body', models.TextField(verbose_name='正文')),
            ],
            options={
                'verbose_name': '新闻',
                'verbose_name_plural': '新闻',
                'ordering': ['-create_time'],
            },
        ),
    ]
