# Generated by Django 2.1.1 on 2018-09-10 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, verbose_name='标题')),
                ('image', models.ImageField(blank=True, upload_to='media/evetsimages', verbose_name='上传交易记录')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': '交易记录',
                'verbose_name_plural': '交易记录',
                'ordering': ['-create_time'],
            },
        ),
    ]
