# Generated by Django 2.1.1 on 2018-09-11 07:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news_base', '0002_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='如张三', max_length=68, verbose_name='姓名')),
                ('tel', models.CharField(default='', max_length=100, verbose_name='电话')),
                ('sub', models.TextField(blank=True, default='如：求职/办理业务', null=True, verbose_name='内容')),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True, verbose_name='邮箱')),
                ('create_time', models.DateField(default=django.utils.timezone.now, verbose_name='时间')),
            ],
            options={
                'verbose_name': '留言信息',
                'verbose_name_plural': '留言信息',
                'ordering': ('-create_time',),
            },
        ),
    ]
