# Generated by Django 2.1.1 on 2018-09-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_base', '0004_auto_20180911_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='简要介绍')),
                ('text', models.TextField(verbose_name='详细介绍')),
                ('img', models.ImageField(upload_to='media/about', verbose_name='配图')),
            ],
        ),
        migrations.RemoveField(
            model_name='imformation',
            name='email',
        ),
        migrations.AlterField(
            model_name='imformation',
            name='sub',
            field=models.TextField(blank=True, default='如：求职/办理业务', null=True, verbose_name='留言'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/newspictures', verbose_name='图片'),
        ),
    ]
