# Generated by Django 2.1.1 on 2018-09-13 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_base', '0005_auto_20180912_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cooperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=128, verbose_name='欢迎合作')),
                ('date', models.DateField(auto_now_add=True, verbose_name='填写日期')),
            ],
            options={
                'verbose_name': '合作邀请文案',
                'verbose_name_plural': '合作邀请文案',
            },
        ),
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': '尚辰保理介绍', 'verbose_name_plural': '尚辰保理介绍'},
        ),
    ]
