# Generated by Django 2.1.1 on 2018-09-13 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_base', '0006_auto_20180913_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperation',
            name='text',
            field=models.TextField(verbose_name='欢迎合作'),
        ),
    ]
