# Generated by Django 2.1.1 on 2018-09-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_base', '0007_auto_20180913_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='业务名称')),
                ('text', models.TextField(verbose_name='服务详细')),
                ('img', models.ImageField(upload_to='media/services', verbose_name='配图')),
                ('creat', models.DateTimeField(auto_now_add=True, verbose_name='编写日期')),
            ],
            options={
                'verbose_name': '服务内容',
                'verbose_name_plural': '服务内容',
                'ordering': ('-creat',),
            },
        ),
    ]
